version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"
    volumes:
      - ./db/mysql/volumes:/var/lib/mysql
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    links:
      - db
    stdin_open: true
    tty: true
  elastic_search:
    image: elasticsearch:5.3
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: always
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
    environment: 
      MINIO_ACCESS_KEY: ak_eight
      MINIO_SECRET_KEY: sk_eight
    restart: always
    command: 
      - server
      - /data
